from pathlib import Path
from rich.console import Console

from hem.builders.scaffold_manager import ScaffoldManager
from hem.runtime.paths import Paths

console = Console()


class InitManager:

    def initialize_project(self, root_dir: Path | None = None) -> Path:
        target = root_dir or Path.cwd()

        # 1. Create project directories
        assets_dir = target / "src" / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)

        providers_dir = target / "src" / "providers"
        providers_dir.mkdir(parents=True, exist_ok=True)

        output_dir = target / "output"
        output_dir.mkdir(parents=True, exist_ok=True)

        docs_dir = target / "docs"
        docs_dir.mkdir(parents=True, exist_ok=True)

        # 2. Create sample asset
        sample_asset = assets_dir / "sample_gateway.yaml"
        if not sample_asset.exists():
            sample_asset.write_text("""asset:
  id: sample_gateway
  name: Sample Gateway
  provider: ping
  class: infrastructure
  type: gateway
  vendor: Generic
  model: Router-X
  location: main_office
  criticality: high
  source:
    availability: binary_sensor.net_sample_gateway
    latency: sensor.net_sample_gateway_latency
    jitter: sensor.net_sample_gateway_jitter
    packet_loss: sensor.net_sample_gateway_packet_loss
""", encoding="utf-8")

        # 3. Create initial README.md if missing
        readme = target / "README.md"
        if not readme.exists():
            readme.write_text("# HEM User Project\n\nGenerated by `hem init`.\n", encoding="utf-8")

        return target
